<?php

declare(strict_types=1);

return [
    'default_locale' => 'pl',

    'segments' => [
        'pl' => [
            'transactions' => 'transakcje',
            'accounts' => 'konta',
            'categories' => 'kategorie',
            'pockets' => 'kieszenie',
            'imports' => 'importy',
            'transfers' => 'transfery',
            'dashboard' => 'panel',
            'settings' => 'ustawienia',
            'budget' => 'budzet',
            'budget.monthly' => 'budzet/miesieczny',
            'budget.yearly' => 'budzet/roczny',
            'settings.profile' => 'ustawienia/profil',
            'settings.password' => 'ustawienia/haslo',
            'settings.appearance' => 'ustawienia/wyglad',
            'accounts.balance' => 'konta/{account}/saldo',
            'categories.reorder' => 'kategorie/kolejnosc',
            'categories.estimates.annual' => 'kategorie/{category}/szacunki/roczny',
            'categories.estimates.monthly' => 'kategorie/{category}/szacunki/miesieczny',
            'categories.estimates.yearly-plan' => 'kategorie/{category}/szacunki/plan-roczny',
            'pockets.reorder' => 'kieszenie/kolejnosc',
            'imports.upload' => 'importy/wgraj',
            'imports.commit' => 'importy/{import}/zatwierdz',
            'imports.failed_rows.dismiss_all' => 'nieudane-wiersze/odrzuc-wszystkie',
            'imports.failed_rows.dismiss' => 'nieudane-wiersze/{importFailedRow}/odrzuc',
            'transfers.create' => 'transfery/utworz',
            'transfers.candidates.confirm' => 'transfery/kandydaci/{transaction}/potwierdz',
            'transfers.candidates.reject' => 'transfery/kandydaci/{transaction}/odrzuc',
            'transfers.unlink' => 'transfery/{transferId}/odlacz',
            'auth.login' => 'logowanie',
            'auth.register' => 'rejestracja',
            'auth.password.request' => 'reset-hasla',
            'auth.password.reset' => 'reset-hasla/{token}',
            'auth.password.store' => 'reset-hasla/zapis',
            'auth.verification.notice' => 'weryfikacja-email',
            'auth.verification.verify' => 'weryfikacja-email/{id}/{hash}',
            'auth.verification.send' => 'email/weryfikacja',
            'auth.password.confirm' => 'potwierdz-haslo',
            'auth.logout' => 'wyloguj',
        ],
        'en' => [
            'transactions' => 'transactions',
            'accounts' => 'accounts',
            'categories' => 'categories',
            'pockets' => 'pockets',
            'imports' => 'imports',
            'transfers' => 'transfers',
            'dashboard' => 'dashboard',
            'settings' => 'settings',
            'budget' => 'budget',
            'budget.monthly' => 'budget/monthly',
            'budget.yearly' => 'budget/yearly',
            'settings.profile' => 'settings/profile',
            'settings.password' => 'settings/password',
            'settings.appearance' => 'settings/appearance',
            'accounts.balance' => 'accounts/{account}/balance',
            'categories.reorder' => 'categories/reorder',
            'categories.estimates.annual' => 'categories/{category}/estimates/annual',
            'categories.estimates.monthly' => 'categories/{category}/estimates/monthly',
            'categories.estimates.yearly-plan' => 'categories/{category}/estimates/yearly-plan',
            'pockets.reorder' => 'pockets/reorder',
            'imports.upload' => 'imports/upload',
            'imports.commit' => 'imports/{import}/commit',
            'imports.failed_rows.dismiss_all' => 'import-failed-rows/dismiss-all',
            'imports.failed_rows.dismiss' => 'import-failed-rows/{importFailedRow}/dismiss',
            'transfers.create' => 'transfers/create',
            'transfers.candidates.confirm' => 'transfers/candidates/{transaction}/confirm',
            'transfers.candidates.reject' => 'transfers/candidates/{transaction}/reject',
            'transfers.unlink' => 'transfers/{transferId}/unlink',
            'auth.login' => 'login',
            'auth.register' => 'register',
            'auth.password.request' => 'forgot-password',
            'auth.password.reset' => 'reset-password/{token}',
            'auth.password.store' => 'reset-password',
            'auth.verification.notice' => 'verify-email',
            'auth.verification.verify' => 'verify-email/{id}/{hash}',
            'auth.verification.send' => 'email/verification-notification',
            'auth.password.confirm' => 'confirm-password',
            'auth.logout' => 'logout',
        ],
    ],
];
