name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer:v2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-progress --prefer-dist
          npm ci

      - name: Run Pint
        run: vendor/bin/pint --test

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Check Frontend Formatting
        run: npm run format:check

      - name: Lint Frontend
        run: npm run lint:check

      - name: Typecheck Frontend
        run: npm run typecheck
